name: List checks

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '23 8 * * 1'

permissions:
  contents: read

jobs:
  awesome-lint:
    name: Awesome lint
    if: github.event_name != 'schedule'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'
          package-manager-cache: false
      - run: npx --yes awesome-lint@2.3.0

  links:
    name: Links
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Check Markdown links
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.9.0
        with:
          args: --config lychee.toml --no-progress './*.md' './.github/*.md'
          lycheeVersion: v0.24.2
          fail: true
          failIfEmpty: true
          jobSummary: true
          output: ${{ runner.temp }}/lychee-report.md
